### ISSUE TITLE
Hitting enter/return after a URL runs it twice and on a different line

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/bold-editor#14]
# Reproduction Steps
1. Place the cursor after the string of a URL
2. Hit the enter/return key.

# What happens
- The URL is hyperlinked. 🎉 
- The cursor appears a 1-2 lines below
- The cursor has broken off text from one of the following lines on to a new line

This affects both mobile and desktop.

**Comment by ningsongshen** [comment]
Hmm sorry I can't seem to reproduce this issue...but do update us with more details on link and text positioning if this issue is still occurring for you.

**Comment by JaspalSuri** [comment]
I think this might have been an issue when links were visually truncated in the Bold Editor. Now that they're left in tact (thanks to your hard work), this issue also doesn't exist, either.
