### ISSUE TITLE
Image pasting in the wrong position and deletes already pasted images.

### ISSUE THREAD

**Issue by csk** [standardnotes/bold-editor#17]
There is an issue when pasting images in the bold editor.

Every time I paste a image from the clipboard it gets pasted at the begging of the note. If a image is moved to another position and a new one is pasted, the first one gets removed.

I attach a gif showing the problem.

![Image pasting issue](https://user-images.githubusercontent.com/153092/74113251-ce2ad780-4b81-11ea-8c44-d93c65562c1e.gif)

Please fix it :-)

**Comment by ningsongshen** [comment]
In doing some testing, I noticed similar issue:

After an already uploaded image is moved to another position, the image will be lost when leaving the note. When going back to the note, the image disappears.

**Comment by mobitar** [comment]
Hmm that's no good. Can replicate. I imagine the two issues will be related? Can you take a look at that as well for this PR?

I can confirm that the PR updates also fix the newline issue.

**Comment by ningsongshen** [comment]
@csk thanks for the bug report! 

You'll find that it's been fixed up in the new release.
https://github.com/standardnotes/bold-editor/releases/tag/1.0.6
