### ISSUE TITLE
Only monospace font works

### ISSUE THREAD

**Issue by SiGamma** [standardnotes/bold-editor#7]
Trying to change the font in the font picker does not seem to do anything and I'm stuck with monospace, on Windows and iOS at least. Is it a known limitation/bug or just something on my end?

**Comment by mobitar** [comment]
I don't see this same behavior. Although I do recall having observed this behavior once, when the text was inside a table, or something similar. What's the nature of the text?

**Comment by SiGamma** [comment]
The note consists of just a few bullet points. 

I tried creating a new note and writing some plain text in there. It still defaults to monospace instead of whatever the Plus, Simple Task etc. editors default to, but I can change the font, although not reliably. For example, if I set it to Arial, and then click Arial again, it seems to switch to Helvetica (I'm terrible with fonts, apologies)? If I keep clicking on Arial it keeps switching between the two. Then, if I click on another font, it might or might not switch to it. Tried to get something reproducible but I'm failing. 

It's really weird behavior, and since I'm bad with fonts and there is no visual indicator to see which font is (supposed to be) currently selected, I assume this isn't of much help to you. Would a screen recording help? 

And of course, if I convert those paragraphs to bullet points, this all goes out the window as it gets stuck on monospace, and clicking on any of the font options does not do anything.

**Comment by lasscap** [comment]
I have the same problem that the font does not change for bullet points and stayes as Monospace (but not quite as it is a bit lower).

Have a look:
![Oct-03-2019 16-44-33](https://user-images.githubusercontent.com/47210775/66137492-755c9880-e5fd-11e9-9ec0-2e338e490cda.gif)

Oh, and having an indicator for the choosen font would be great! :)
