### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by TROMsite** [standardnotes/bold-editor#78]
I see there is no way to resize images. Could be very useful since at times they take up the entire width of the note.

**Comment by JaspalSuri** [comment]
Hi @TROMsite, sorry for the delayed response. You can resize images in the Bold Editor by clicking or tapping on them and then press & drag the anchor up (located in the bottom right corner) up or down diagonally to resize the image.

**Comment by TROMsite** [comment]
Ah I apologize I meant to post this for the Plus Editor. Is the Plus Editor managed by you or you use it as a third party extension? So I know if I should post the issue via standardnotes or not. Thanks!

**Comment by JaspalSuri** [comment]
No worries! The Plus Editor is derived from [summernote](https://github.com/summernote/summernote/). You can create a request [here](https://github.com/summernote/summernote/issues). 🙂

**Comment by TROMsite** [comment]
Thank you I will!
