### ISSUE TITLE
Scrolling on one note, scrolls on another.

### ISSUE THREAD

**Issue by tio-trom** [standardnotes/bold-editor#80]
This is a weird bug but if I scroll down on one note that has the Bold Editor active, then switch to another note that has the same Bold Editor active, it scroll down on that one too. Down or up doesn't matter. But if there are different editors it won't happen. Only happens with the Bold editor.

Tested on Arch Linux with this https://aur.archlinux.org/packages/standardnotes-bin/

**Comment by JaspalSuri** [comment]
Hi @TROMsite, thank you for letting us know! I was able to reproduce the issue and will create a report for the dev team to review. 🙂
